export const atoms = [
  {
    elemento: 'Hidrogênio',
    simbolo: 'H',
    descricao: 'Um elemento não metálico e altamente inflamável. É o elemento mais leve e abundante no universo.',
    massa: 1.01,
    estado: 'Gasoso',
    eletrons: [1],
    protons: 1,
    neutrons: 0,
    grupo: 1,
    periodo: 1,
    bloco: 's'
  },

  {
    elemento: 'Hélio',
    simbolo: 'He',
    descricao: 'Um gás nobre incolor e inodoro. É o segundo elemento mais leve e o segundo mais abundante no universo.',
    massa: 4.00,
    estado: 'Gasoso',
    eletrons: [2],
    protons: 2,
    neutrons: 2,
    grupo: 18,
    periodo: 1,
    bloco: 's'
  },

  {
    elemento: 'Lítio',
    simbolo: 'Li',
    descricao: 'Um metal alcalino macio e prateado. É o metal mais leve e possui alta reatividade química.',
    massa: 6.94,
    estado: 'Sólido',
    eletrons: [2, 1],
    protons: 3,
    neutrons: 4,
    grupo: 1,
    periodo: 2,
    bloco: 's'
  },

  {
    elemento: 'Berílio',
    simbolo: 'Be',
    descricao: 'Um metal alcalino-terroso rígido, leve e quebradiço. Possui alta resistência à corrosão.',
    massa: 9.01,
    estado: 'Sólido',
    eletrons: [2, 2],
    protons: 4,
    neutrons: 5,
    grupo: 2,
    periodo: 2,
    bloco: 's'
  },

  {
    elemento: 'Boro',
    simbolo: 'B',
    descricao: 'Um sólido marrom não metálico que é um semicondutor. É um elemento essencial na formação de compostos orgânicos e inorgânicos.',
    massa: 10.81,
    estado: 'Sólido',
    eletrons: [2, 3],
    protons: 5,
    neutrons: 6,
    grupo: 13,
    periodo: 2,
    bloco: 'p'
  },
  {
    elemento: 'Carbono',
    simbolo: 'C',
    descricao: 'Um não metal que é o bloco de construção fundamental da química orgânica. É encontrado em várias formas, incluindo grafite e diamante.',
    massa: 12.01,
    estado: 'Sólido',
    eletrons: [2, 4],
    protons: 6,
    neutrons: 6,
    grupo: 14,
    periodo: 2,
    bloco: 'p'
  },
  {
    elemento: 'Nitrogênio',
    simbolo: 'N',
    descricao: 'Um gás diatômico incolor e inodoro. É um componente essencial de proteínas e ácidos nucleicos.',
    massa: 14.01,
    estado: 'Gasoso',
    eletrons: [2, 5],
    protons: 7,
    neutrons: 7,
    grupo: 15,
    periodo: 2,
    bloco: 'p'
  },
  {
    elemento: 'Oxigênio',
    simbolo: 'O',
    descricao: 'Um gás diatômico essencial para a respiração aeróbica. É o terceiro elemento mais abundante no universo.',
    massa: 16.00,
    estado: 'Gasoso',
    eletrons: [2, 6],
    protons: 8,
    neutrons: 8,
    grupo: 16,
    periodo: 2,
    bloco: 'p'
  },
  {
    elemento: 'Flúor',
    simbolo: 'F',
    descricao: 'Um gás amarelo-pálido extremamente reativo. É o elemento mais eletronegativo e corrosivo conhecido.',
    massa: 19.00,
    estado: 'Gasoso',
    eletrons: [2, 7],
    protons: 9,
    neutrons: 10,
    grupo: 17,
    periodo: 2,
    bloco: 'p'
  },
  {
    elemento: 'Neônio',
    simbolo: 'Ne',
    descricao: 'Um gás nobre incolor e inodoro. É usado em sinais luminosos e displays de tubos de descarga.',
    massa: 20.18,
    estado: 'Gasoso',
    eletrons: [2, 8],
    protons: 10,
    neutrons: 10,
    grupo: 18,
    periodo: 2,
    bloco: 'p'
  },
  {
    elemento: 'Sódio',
    simbolo: 'Na',
    descricao: 'Um metal alcalino macio e prateado. É altamente reativo e é essencial para a saúde do corpo humano.',
    massa: 22.99,
    estado: 'Sólido',
    eletrons: [2, 8, 1],
    protons: 11,
    neutrons: 12,
    grupo: 1,
    periodo: 3,
    bloco: 's'
  },
  {
    elemento: 'Magnésio',
    simbolo: 'Mg',
    descricao: 'Um metal alcalino-terroso leve, prateado e bastante abundante. É essencial para muitos processos biológicos.',
    massa: 24.31,
    estado: 'Sólido',
    eletrons: [2, 8, 2],
    protons: 12,
    neutrons: 12,
    grupo: 2,
    periodo: 3,
    bloco: 's'
  },
  {
    elemento: 'Alumínio',
    simbolo: 'Al',
    descricao: 'Um metal leve, prateado e resistente à corrosão. É usado em uma ampla variedade de aplicações industriais.',
    massa: 26.98,
    estado: 'Sólido',
    eletrons: [2, 8, 3],
    protons: 13,
    neutrons: 14,
    grupo: 13,
    periodo: 3,
    bloco: 'p'
  },
  {
    elemento: 'Silício',
    simbolo: 'Si',
    descricao: 'Um sólido cinza-escuro semicondutor. É um elemento essencial para a indústria eletrônica.',
    massa: 28.09,
    estado: 'Sólido',
    eletrons: [2, 8, 4],
    protons: 14,
    neutrons: 14,
    grupo: 14,
    periodo: 3,
    bloco: 'p'
  },
  {
    elemento: 'Fósforo',
    simbolo: 'P',
    descricao: 'Um sólido vermelho brilhante que exibe fosforescência. É um elemento essencial para a vida e é encontrado no DNA e RNA.',
    massa: 30.97,
    estado: 'Sólido',
    eletrons: [2, 8, 5],
    protons: 15,
    neutrons: 16,
    grupo: 15,
    periodo: 3,
    bloco: 'p'
  },
  {
    elemento: 'Enxofre',
    simbolo: 'S',
    descricao: 'Um sólido amarelo com um odor característico. É um elemento essencial para várias moléculas biológicas.',
    massa: 32.07,
    estado: 'Sólido',
    eletrons: [2, 8, 6],
    protons: 16,
    neutrons: 16,
    grupo: 16,
    periodo: 3,
    bloco: 'p'
  },
  {
    elemento: 'Cloro',
    simbolo: 'Cl',
    descricao: 'Um gás amarelo-verde altamente reativo. É um componente essencial do sal de cozinha e é usado como desinfetante.',
    massa: 35.45,
    estado: 'Gasoso',
    eletrons: [2, 8, 7],
    protons: 17,
    neutrons: 18,
    grupo: 17,
    periodo: 3,
    bloco: 'p'
  },
  {
    elemento: 'Argônio',
    simbolo: 'Ar',
    descricao: 'Um gás nobre incolor e inodoro. É usado em lâmpadas de luz de néon e na soldagem.',
    massa: 39.95,
    estado: 'Gasoso',
    eletrons: [2, 8, 8],
    protons: 18,
    neutrons: 22,
    grupo: 18,
    periodo: 3,
    bloco: 'p'
  },
  {
    elemento: 'Potássio',
    simbolo: 'K',
    descricao: 'Um metal alcalino macio e prateado. É altamente reativo e é encontrado em muitos minerais e tecidos vivos.',
    massa: 39.10,
    estado: 'Sólido',
    eletrons: [2, 8, 8, 1],
    protons: 19,
    neutrons: 20,
    grupo: 1,
    periodo: 4,
    bloco: 's'
  },
  {
    elemento: 'Cálcio',
    simbolo: 'Ca',
    descricao: 'Um metal alcalino-terroso prateado e macio. É essencial para a saúde dos ossos e dos dentes.',
    massa: 40.08,
    estado: 'Sólido',
    eletrons: [2, 8, 8, 2],
    protons: 20,
    neutrons: 20,
    grupo: 2,
    periodo: 4,
    bloco: 's'
  },
  {
    elemento: 'Escândio',
    simbolo: 'Sc',
    descricao: 'Um metal prateado brilhante e macio. É usado em aplicações como lâmpadas de alta intensidade e ligas metálicas.',
    massa: 44.96,
    estado: 'Sólido',
    eletrons: [2, 8, 9, 2],
    protons: 21,
    neutrons: 24,
    grupo: 3,
    periodo: 4,
    bloco: 'd'
  },
  {
    elemento: 'Titânio',
    simbolo: 'Ti',
    descricao: 'Um metal de transição forte e de baixa densidade. É usado em ligas metálicas e implantes médicos.',
    massa: 47.87,
    estado: 'Sólido',
    eletrons: [2, 8, 10, 2],
    protons: 22,
    neutrons: 26,
    grupo: 4,
    periodo: 4,
    bloco: 'd'
  },
  {
    elemento: 'Vanádio',
    simbolo: 'V',
    descricao: 'Um metal de transição prateado e duro. É usado em ligas metálicas resistentes e em baterias recarregáveis.',
    massa: 50.94,
    estado: 'Sólido',
    eletrons: [2, 8, 11, 2],
    protons: 23,
    neutrons: 28,
    grupo: 5,
    periodo: 4,
    bloco: 'd'
  },
  {
    elemento: 'Crômio',
    simbolo: 'Cr',
    descricao: 'Um metal de transição duro e resistente à corrosão. É usado em ligas metálicas e na produção de aço inoxidável.',
    massa: 52.00,
    estado: 'Sólido',
    eletrons: [2, 8, 13, 1],
    protons: 24,
    neutrons: 28,
    grupo: 6,
    periodo: 4,
    bloco: 'd'
  },
  {
    elemento: 'Manganês',
    simbolo: 'Mn',
    descricao: 'Um metal de transição prateado brilhante. É usado em ligas metálicas, baterias e como catalisador.',
    massa: 54.94,
    estado: 'Sólido',
    eletrons: [2, 8, 13, 2],
    protons: 25,
    neutrons: 30,
    grupo: 7,
    periodo: 4,
    bloco: 'd'
  },
  {
    elemento: 'Ferro',
    simbolo: 'Fe',
    descricao: 'Um metal de transição prateado e maleável. É um elemento essencial na formação de aço.',
    massa: 55.85,
    estado: 'Sólido',
    eletrons: [2, 8, 14, 2],
    protons: 26,
    neutrons: 30,
    grupo: 8,
    periodo: 4,
    bloco: 'd'
  },
  {
    elemento: 'Cobalto',
    simbolo: 'Co',
    descricao: 'Um metal de transição duro, magnético e de cor prateada. É usado em ligas metálicas e na indústria de baterias.',
    massa: 58.93,
    estado: 'Sólido',
    eletrons: [2, 8, 15, 2],
    protons: 27,
    neutrons: 32,
    grupo: 9,
    periodo: 4,
    bloco: 'd'
  },
  {
    elemento: 'Níquel',
    simbolo: 'Ni',
    descricao: 'Um metal de transição prateado brilhante e resistente à corrosão. É usado em ligas metálicas e em moedas.',
    massa: 58.69,
    estado: 'Sólido',
    eletrons: [2, 8, 16, 2],
    protons: 28,
    neutrons: 31,
    grupo: 10,
    periodo: 4,
    bloco: 'd'
  },
  {
    elemento: 'Cobre',
    simbolo: 'Cu',
    descricao: 'Um metal de transição vermelho-alaranjado brilhante. É um excelente condutor de eletricidade.',
    massa: 63.55,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 1],
    protons: 29,
    neutrons: 35,
    grupo: 11,
    periodo: 4,
    bloco: 'd'
  },
  {
    elemento: 'Zinco',
    simbolo: 'Zn',
    descricao: 'Um metal de transição azul-acinzentado. É usado em ligas metálicas, em galvanização e em pilhas.',
    massa: 65.38,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 2],
    protons: 30,
    neutrons: 35,
    grupo: 12,
    periodo: 4,
    bloco: 'd'
  },
  {
    elemento: 'Gálio',
    simbolo: 'Ga',
    descricao: 'Um metal macio, prateado e semicondutor. É usado em dispositivos optoeletrônicos e lasers.',
    massa: 69.72,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 3],
    protons: 31,
    neutrons: 39,
    grupo: 13,
    periodo: 4,
    bloco: 'p'
  },
  {
    elemento: 'Germânio',
    simbolo: 'Ge',
    descricao: 'Um semimetal cinza-acinzentado. É usado em dispositivos semicondutores e em óptica.',
    massa: 72.63,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 4],
    protons: 32,
    neutrons: 41,
    grupo: 14,
    periodo: 4,
    bloco: 'p'
  },
  {
    elemento: 'Arsênio',
    simbolo: 'As',
    descricao: 'Um sólido cinza metálico brilhante ou amarelo-acinzentado. É um elemento tóxico e semicondutor.',
    massa: 74.92,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 5],
    protons: 33,
    neutrons: 42,
    grupo: 15,
    periodo: 4,
    bloco: 'p'
  },
  {
    elemento: 'Selênio',
    simbolo: 'Se',
    descricao: 'Um sólido cinza-escuro ou vermelho. É um elemento essencial para a vida e tem propriedades fotovoltaicas.',
    massa: 78.97,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 6],
    protons: 34,
    neutrons: 45,
    grupo: 16,
    periodo: 4,
    bloco: 'p'
  },
  {
    elemento: 'Bromo',
    simbolo: 'Br',
    descricao: 'Um líquido vermelho escuro volátil. É um elemento corrosivo e tóxico.',
    massa: 79.90,
    estado: 'Líquido',
    eletrons: [2, 8, 18, 7],
    protons: 35,
    neutrons: 45,
    grupo: 17,
    periodo: 4,
    bloco: 'p'
  },
  {
    elemento: 'Criptônio',
    simbolo: 'Kr',
    descricao: 'Um gás nobre incolor e inodoro. É usado em lâmpadas de néon e em lasers.',
    massa: 83.80,
    estado: 'Gasoso',
    eletrons: [2, 8, 18, 8],
    protons: 36,
    neutrons: 48,
    grupo: 18,
    periodo: 4,
    bloco: 'p'
  },
  {
    elemento: 'Rubídio',
    simbolo: 'Rb',
    descricao: 'Um metal alcalino macio e prateado. É altamente reativo e é usado em células fotoelétricas e em foguetes.',
    massa: 85.47,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 8, 1],
    protons: 37,
    neutrons: 48,
    grupo: 1,
    periodo: 5,
    bloco: 's'
  },
  {
    elemento: 'Estrôncio',
    simbolo: 'Sr',
    descricao: 'Um metal alcalino-terroso prateado. É usado em fogos de artifício e em aplicações médicas.',
    massa: 87.62,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 8, 2],
    protons: 38,
    neutrons: 50,
    grupo: 2,
    periodo: 5,
    bloco: 's'
  },
  {
    elemento: 'Ítrio',
    simbolo: 'Y',
    descricao: 'Um metal de transição prateado, macio e maleável.',
    massa: 88.90584,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 9, 2],
    protons: 39,
    neutrons: 50,
    grupo: 3,
    periodo: 5,
    bloco: 'd'
  },
  {
    elemento: 'Zircônio',
    simbolo: 'Zr',
    descricao: 'Um metal de transição branco-prateado. É muito resistente à corrosão e é usado em ligas.',
    massa: 91.224,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 10, 2],
    protons: 40,
    neutrons: 51,
    grupo: 4,
    periodo: 5,
    bloco: 'd'
  },
  {
    elemento: 'Nióbio',
    simbolo: 'Nb',
    descricao: 'Um metal de transição cinza-branco. É frequentemente usado em ligas devido à sua alta resistência.',
    massa: 92.90638,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 12, 1],
    protons: 41,
    neutrons: 52,
    grupo: 5,
    periodo: 5,
    bloco: 'd'
  },
  {
    elemento: 'Molibdênio',
    simbolo: 'Mo',
    descricao: 'Um metal de transição prateado. É usado em várias aplicações industriais, como em aços de alta resistência.',
    massa: 95.95,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 13, 1],
    protons: 42,
    neutrons: 53,
    grupo: 6,
    periodo: 5,
    bloco: 'd'
  },
  {
    elemento: 'Tecnécio',
    simbolo: 'Tc',
    descricao: 'Um elemento radioativo e prateado. É usado em imagens médicas.',
    massa: 98,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 13, 2],
    protons: 43,
    neutrons: 55,
    grupo: 7,
    periodo: 5,
    bloco: 'd'
  },
  {
    elemento: 'Rutênio',
    simbolo: 'Ru',
    descricao: 'Um metal de transição branco-prateado. É usado em catalisadores, resistências elétricas e joias.',
    massa: 101.07,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 15, 1],
    protons: 44,
    neutrons: 57,
    grupo: 8,
    periodo: 5,
    bloco: 'd'
  },
  {
    elemento: 'Ródio',
    simbolo: 'Rh',
    descricao: 'Um metal de transição prateado brilhante. É usado em catalisadores, joias e em algumas moedas.',
    massa: 102.90550,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 16, 1],
    protons: 45,
    neutrons: 58,
    grupo: 9,
    periodo: 5,
    bloco: 'd'
  },
  {
    elemento: 'Paládio',
    simbolo: 'Pd',
    descricao: 'Um metal de transição branco-prateado. É usado em joias, catalisadores e em odontologia.',
    massa: 106.42,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 18],
    protons: 46,
    neutrons: 60,
    grupo: 10,
    periodo: 5,
    bloco: 'd'
  },
  {
    elemento: 'Prata',
    simbolo: 'Ag',
    descricao: 'Um metal de transição branco-prateado. É usado em joias, moedas e em várias aplicações industriais.',
    massa: 107.8682,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 18, 1],
    protons: 47,
    neutrons: 61,
    grupo: 11,
    periodo: 5,
    bloco: 'd'
  },
  {
    elemento: 'Cádmio',
    simbolo: 'Cd',
    descricao: 'Um metal de transição branco-azulado. É usado em baterias, pigmentos e revestimentos.',
    massa: 112.414,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 18, 2],
    protons: 48,
    neutrons: 64,
    grupo: 12,
    periodo: 5,
    bloco: 'd'
  },
  {
    elemento: 'Índio',
    simbolo: 'In',
    descricao: 'Um metal pós-transição cinza-prateado. É usado em telas de cristal líquido, em semicondutores e em ligas.',
    massa: 114.818,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 18, 3],
    protons: 49,
    neutrons: 66,
    grupo: 13,
    periodo: 5,
    bloco: 'p'
  },
  {
    elemento: 'Estanho',
    simbolo: 'Sn',
    descricao: 'Um metal pós-transição prateado-branco. É usado em soldas, em revestimentos protetores e em ligas metálicas.',
    massa: 118.710,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 18, 4],
    protons: 50,
    neutrons: 68,
    grupo: 14,
    periodo: 5,
    bloco: 'p'
  },
  {
    elemento: 'Antimônio',
    simbolo: 'Sb',
    descricao: 'Um metaloide branco prateado. É usado em ligas, em retardantes de chama e em produtos de vidro.',
    massa: 121.760,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 18, 5],
    protons: 51,
    neutrons: 70,
    grupo: 15,
    periodo: 5,
    bloco: 'p'
  },
  {
    elemento: 'Telúrio',
    simbolo: 'Te',
    descricao: 'Um metaloide prateado. É usado em ligas, em semicondutores e em alguns vidros.',
    massa: 127.60,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 18, 6],
    protons: 52,
    neutrons: 76,
    grupo: 16,
    periodo: 5,
    bloco: 'p'
  },
  {
    elemento: 'Iodo',
    simbolo: 'I',
    descricao: 'Um halogênio azul-negro sólido. É usado em tinturas, em tratamentos médicos e em alguns processos químicos.',
    massa: 126.90447,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 18, 7],
    protons: 53,
    neutrons: 74,
    grupo: 17,
    periodo: 5,
    bloco: 'p'
  },
  {
    elemento: 'Xenônio',
    simbolo: 'Xe',
    descricao: 'Um gás nobre incolor e inodoro. É usado em lâmpadas, em dispositivos de ressonância magnética e em lasers.',
    massa: 131.293,
    estado: 'Gasoso',
    eletrons: [2, 8, 18, 18, 8],
    protons: 54,
    neutrons: 77,
    grupo: 18,
    periodo: 5,
    bloco: 'p'
  },
  {
    elemento: 'Césio',
    simbolo: 'Cs',
    descricao: 'Um metal alcalino dourado. É usado em relógios atômicos, em fotoeletrodos e em propulsores iônicos.',
    massa: 132.90545196,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 18, 8, 1],
    protons: 55,
    neutrons: 78,
    grupo: 1,
    periodo: 6,
    bloco: 's'
  },
  {
    elemento: 'Bário',
    simbolo: 'Ba',
    descricao: 'Um metal alcalino-terroso prateado. É usado em ligas metálicas, em medicamentos e em aplicações industriais.',
    massa: 137.327,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 18, 8, 2],
    protons: 56,
    neutrons: 81,
    grupo: 2,
    periodo: 6,
    bloco: 's'
  },
  {
    elemento: 'Lantânio',
    simbolo: 'La',
    descricao: 'Um metal de transição prateado-branco. É usado em lâmpadas, em ímãs de alta resistência e em cerâmicas.',
    massa: 138.90547,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 18, 9, 2],
    protons: 57,
    neutrons: 82,
    grupo: 3,
    periodo: 6,
    bloco: 'f'
  },
  {
    elemento: 'Cério',
    simbolo: 'Ce',
    descricao: 'Um metal de transição prateado-branco. É usado em catalisadores, em óculos e em lâmpadas de arco de carbono.',
    massa: 140.116,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 19, 9, 2],
    protons: 58,
    neutrons: 82,
    grupo: 4,
    periodo: 6,
    bloco: 'f'
  },
  {
    elemento: 'Praseodímio',
    simbolo: 'Pr',
    descricao: 'Um metal de transição prateado-branco. É usado em ligas de magnésio e alumínio, em cerâmicas e em vidros.',
    massa: 140.90766,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 21, 8, 2],
    protons: 59,
    neutrons: 82,
    grupo: 5,
    periodo: 6,
    bloco: 'f'
  },
  {
    elemento: 'Neodímio',
    simbolo: 'Nd',
    descricao: 'Um metal de transição prateado. É usado em ligas permanentes de ímãs, em cerâmicas e em vidros.',
    massa: 144.242,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 22, 8, 2],
    protons: 60,
    neutrons: 84,
    grupo: 6,
    periodo: 6,
    bloco: 'f'
  },
  {
    elemento: 'Promécio',
    simbolo: 'Pm',
    descricao: 'Um elemento radioativo e prateado. É usado em fontes de energia nuclear e em dispositivos médicos.',
    massa: 145,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 23, 8, 2],
    protons: 61,
    neutrons: 84,
    grupo: 7,
    periodo: 6,
    bloco: 'f'
  },
  {
    elemento: 'Samário',
    simbolo: 'Sm',
    descricao: 'Um metal de transição prateado. É usado em ímãs permanentes, em catalisadores e em vidros de laser.',
    massa: 150.36,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 24, 8, 2],
    protons: 62,
    neutrons: 88,
    grupo: 8,
    periodo: 6,
    bloco: 'f'
  },
  {
    elemento: 'Európio',
    simbolo: 'Eu',
    descricao: 'Um metal de transição prateado. É usado em ímãs permanentes, em dispositivos de segurança e em fósforos de TV.',
    massa: 151.964,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 25, 8, 2],
    protons: 63,
    neutrons: 89,
    grupo: 9,
    periodo: 6,
    bloco: 'f'
  },
  {
    elemento: 'Gadolínio',
    simbolo: 'Gd',
    descricao: 'Um metal de transição prateado. É usado em ímãs permanentes, em reatores nucleares e em detectores de raio-X.',
    massa: 157.25,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 25, 9, 2],
    protons: 64,
    neutrons: 93,
    grupo: 10,
    periodo: 6,
    bloco: 'f'
  },
  {
    elemento: 'Térbio',
    simbolo: 'Tb',
    descricao: 'Um metal de transição prateado. É usado em ímãs permanentes, em dispositivos ópticos e em dispositivos médicos.',
    massa: 158.92535,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 27, 8, 2],
    protons: 65,
    neutrons: 94,
    grupo: 11,
    periodo: 6,
    bloco: 'f'
  },
  {
    elemento: 'Disprósio',
    simbolo: 'Dy',
    descricao: 'Um metal de transição prateado. É usado em ímãs permanentes, em iluminação e em lasers.',
    massa: 162.500,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 28, 8, 2],
    protons: 66,
    neutrons: 96,
    grupo: 12,
    periodo: 6,
    bloco: 'f'
  },
  {
    elemento: 'Hólmio',
    simbolo: 'Ho',
    descricao: 'Um metal de transição prateado. É usado em ímãs permanentes, em dispositivos ópticos e em dispositivos médicos.',
    massa: 164.93033,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 29, 8, 2],
    protons: 67,
    neutrons: 97,
    grupo: 13,
    periodo: 6,
    bloco: 'f'
  },
  {
    elemento: 'Erbio',
    simbolo: 'Er',
    descricao: 'Um metal de transição prateado. É usado em ímãs permanentes, em fibras ópticas e em dispositivos médicos.',
    massa: 167.259,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 30, 8, 2],
    protons: 68,
    neutrons: 99,
    grupo: 14,
    periodo: 6,
    bloco: 'f'
  },
  {
    elemento: 'Túlio',
    simbolo: 'Tm',
    descricao: 'Um metal de transição prateado. É usado em ímãs permanentes, em dispositivos ópticos e em dispositivos médicos.',
    massa: 168.93422,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 31, 8, 2],
    protons: 69,
    neutrons: 100,
    grupo: 15,
    periodo: 6,
    bloco: 'f'
  },
  {
    elemento: 'Itérbio',
    simbolo: 'Yb',
    descricao: 'Um metal de transição prateado macio. É usado em ligas metálicas e em aplicações médicas.',
    massa: 173.04,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 8, 2],
    protons: 70,
    neutrons: 103,
    grupo: 3,
    periodo: 6,
    bloco: 'f'
  },
  {
    elemento: 'Háfnio',
    simbolo: 'Hf',
    descricao: 'Um metal de transição prateado brilhante. É usado em ligas metálicas de alta temperatura e em reatores nucleares.',
    massa: 178.49,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 10, 2],
    protons: 72,
    neutrons: 106,
    grupo: 4,
    periodo: 6,
    bloco: 'd'
  },
  {
    elemento: 'Tântalo',
    simbolo: 'Ta',
    descricao: 'Um metal de transição cinza-azulado brilhante. É usado em ligas metálicas de alta resistência e em capacitores.',
    massa: 180.95,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 11, 2],
    protons: 73,
    neutrons: 108,
    grupo: 5,
    periodo: 6,
    bloco: 'd'
  },
  {
    elemento: 'Tungstênio',
    simbolo: 'W',
    descricao: 'Um metal de transição cinza-escuro brilhante. É usado em ligas metálicas resistentes e em filamentos de lâmpadas.',
    massa: 183.84,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 12, 2],
    protons: 74,
    neutrons: 110,
    grupo: 6,
    periodo: 6,
    bloco: 'd'
  },
  {
    elemento: 'Rênio',
    simbolo: 'Re',
    descricao: 'Um metal de transição cinza-branco brilhante. É usado em ligas metálicas de alta temperatura e em catalisadores.',
    massa: 186.21,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 13, 2],
    protons: 75,
    neutrons: 111,
    grupo: 7,
    periodo: 6,
    bloco: 'd'
  },
  {
    elemento: 'Ósmio',
    simbolo: 'Os',
    descricao: 'Um metal de transição azul-acinzentado duro e resistente à corrosão. É usado em ligas metálicas e em instrumentos de escrita.',
    massa: 190.23,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 14, 2],
    protons: 76,
    neutrons: 114,
    grupo: 8,
    periodo: 6,
    bloco: 'd'
  },
  {
    elemento: 'Irídio',
    simbolo: 'Ir',
    descricao: 'Um metal de transição branco-prateado muito denso e duro. É usado em ligas metálicas e em penas de caneta.',
    massa: 192.22,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 15, 2],
    protons: 77,
    neutrons: 115,
    grupo: 9,
    periodo: 6,
    bloco: 'd'
  },
  {
    elemento: 'Platina',
    simbolo: 'Pt',
    descricao: 'Um metal de transição cinza-branco brilhante. É usado em joias, em catalisadores e em implantes médicos.',
    massa: 195.08,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 17, 1],
    protons: 78,
    neutrons: 117,
    grupo: 10,
    periodo: 6,
    bloco: 'd'
  },
  {
    elemento: 'Ouro',
    simbolo: 'Au',
    descricao: 'Um metal amarelo brilhante e maleável. É valorizado por sua beleza e é usado em joias e em aplicações eletrônicas.',
    massa: 196.97,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 18, 1],
    protons: 79,
    neutrons: 118,
    grupo: 11,
    periodo: 6,
    bloco: 'd'
  },
  {
    elemento: 'Mercúrio',
    simbolo: 'Hg',
    descricao: 'Um metal líquido prateado. É altamente tóxico e é usado em termômetros e em lâmpadas fluorescentes.',
    massa: 200.59,
    estado: 'Líquido',
    eletrons: [2, 8, 18, 32, 18, 2],
    protons: 80,
    neutrons: 121,
    grupo: 12,
    periodo: 6,
    bloco: 'd'
  },
  {
    elemento: 'Tálio',
    simbolo: 'Tl',
    descricao: 'Um metal macio e maleável de cor cinza-azulada. É usado em aparelhos eletrônicos e em vidros especiais.',
    massa: 204.38,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 18, 3],
    protons: 81,
    neutrons: 123,
    grupo: 13,
    periodo: 6,
    bloco: 'p'
  },
  {
    elemento: 'Chumbo',
    simbolo: 'Pb',
    descricao: 'Um metal cinza-azulado brilhante. É altamente denso e é usado em aplicações como baterias e em soldagem.',
    massa: 207.2,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 18, 4],
    protons: 82,
    neutrons: 125,
    grupo: 14,
    periodo: 6,
    bloco: 'p'
  },
  {
    elemento: 'Bismuto',
    simbolo: 'Bi',
    descricao: 'Um sólido branco prateado rosado. É um dos elementos mais densos e é usado em ligas metálicas e em cosméticos.',
    massa: 208.98,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 18, 5],
    protons: 83,
    neutrons: 126,
    grupo: 15,
    periodo: 6,
    bloco: 'p'
  },
  {
    elemento: 'Polônio',
    simbolo: 'Po',
    descricao: 'Um sólido prateado metálico. É altamente radioativo e ocorre em traços na crosta terrestre.',
    massa: 209,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 18, 6],
    protons: 84,
    neutrons: 125,
    grupo: 16,
    periodo: 6,
    bloco: 'p'
  },
  {
    elemento: 'Astato',
    simbolo: 'At',
    descricao: 'Um sólido radioativo de cor escura. É um dos elementos mais raros e é produzido artificialmente.',
    massa: 210,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 18, 7],
    protons: 85,
    neutrons: 125,
    grupo: 17,
    periodo: 6,
    bloco: 'p'
  },
  {
    elemento: 'Radônio',
    simbolo: 'Rn',
    descricao: 'Um gás nobre incolor e radioativo. É usado em terapias de radioterapia e em pesquisas científicas.',
    massa: 222,
    estado: 'Gasoso',
    eletrons: [2, 8, 18, 32, 18, 8],
    protons: 86,
    neutrons: 136,
    grupo: 18,
    periodo: 6,
    bloco: 'p'
  },
  {
    elemento: 'Frâncio',
    simbolo: 'Fr',
    descricao: 'Um metal alcalino macio e altamente radioativo. É extremamente raro e tem uma vida útil curta.',
    massa: 223,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 18, 8, 1],
    protons: 87,
    neutrons: 136,
    grupo: 1,
    periodo: 7,
    bloco: 's'
  },
  {
    elemento: 'Rádio',
    simbolo: 'Ra',
    descricao: 'Um metal alcalino-terroso branco prateado. É altamente radioativo e é usado em tratamentos médicos.',
    massa: 226,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 18, 8, 2],
    protons: 88,
    neutrons: 138,
    grupo: 2,
    periodo: 7,
    bloco: 's'
  },
  {
    elemento: 'Actínio',
    simbolo: 'Ac',
    descricao: 'Um metal prateado brilhante. É altamente radioativo e é usado em pesquisa científica e em aplicações médicas.',
    massa: 227,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 18, 9, 2],
    protons: 89,
    neutrons: 138,
    grupo: 3,
    periodo: 7,
    bloco: 'f'
  },
  {
    elemento: 'Tório',
    simbolo: 'Th',
    descricao: 'Um metal cinza prateado. É usado em reatores nucleares e em lentes de câmeras de alta qualidade.',
    massa: 232.04,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 18, 10, 2],
    protons: 90,
    neutrons: 142,
    grupo: 4,
    periodo: 7,
    bloco: 'f'
  },
  {
    elemento: 'Protactínio',
    simbolo: 'Pa',
    descricao: 'Um metal prateado brilhante. É altamente radioativo e é usado em pesquisa científica e em reatores nucleares.',
    massa: 231.04,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 20, 9, 2],
    protons: 91,
    neutrons: 140,
    grupo: 5,
    periodo: 7,
    bloco: 'f'
  },
  {
    elemento: 'Urânio',
    simbolo: 'U',
    descricao: 'Um metal prateado denso. É altamente radioativo e é usado em reatores nucleares e na produção de armas nucleares.',
    massa: 238.03,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 21, 9, 2],
    protons: 92,
    neutrons: 146,
    grupo: 6,
    periodo: 7,
    bloco: 'f'
  },
  {
    elemento: 'Neptúnio',
    simbolo: 'Np',
    descricao: 'Um metal prateado brilhante. É altamente radioativo e é usado em reatores nucleares e em pesquisas científicas.',
    massa: 237,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 22, 9, 2],
    protons: 93,
    neutrons: 144,
    grupo: 7,
    periodo: 7,
    bloco: 'f'
  },
  {
    elemento: 'Plutônio',
    simbolo: 'Pu',
    descricao: 'Um metal prateado brilhante. É altamente radioativo e é usado em reatores nucleares e na produção de armas nucleares.',
    massa: 244,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 24, 8, 2],
    protons: 94,
    neutrons: 150,
    grupo: 8,
    periodo: 7,
    bloco: 'f'
  },
  {
    elemento: 'Amerício',
    simbolo: 'Am',
    descricao: 'Um metal prateado brilhante. É altamente radioativo e é usado em reatores nucleares e em pesquisas científicas.',
    massa: 243,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 25, 8, 2],
    protons: 95,
    neutrons: 148,
    grupo: 9,
    periodo: 7,
    bloco: 'f'
  },
  {
    elemento: 'Cúrio',
    simbolo: 'Cm',
    descricao: 'Um metal prateado brilhante. É altamente radioativo e é usado em reatores nucleares e em pesquisas científicas.',
    massa: 247,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 25, 9, 2],
    protons: 96,
    neutrons: 151,
    grupo: 10,
    periodo: 7,
    bloco: 'f'
  },
  {
    elemento: 'Berquélio',
    simbolo: 'Bk',
    descricao: 'Um metal prateado brilhante. É altamente radioativo e é usado em reatores nucleares e em pesquisas científicas.',
    massa: 247,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 27, 8, 2],
    protons: 97,
    neutrons: 150,
    grupo: 11,
    periodo: 7,
    bloco: 'f'
  },
  {
    elemento: 'Califórnio',
    simbolo: 'Cf',
    descricao: 'Um metal prateado brilhante. É altamente radioativo e é usado em reatores nucleares e em pesquisas científicas.',
    massa: 251,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 28, 8, 2],
    protons: 98,
    neutrons: 153,
    grupo: 12,
    periodo: 7,
    bloco: 'f'
  },
  {
    elemento: 'Einstênio',
    simbolo: 'Es',
    descricao: 'Um metal prateado brilhante. É altamente radioativo e é usado em pesquisas científicas.',
    massa: 252,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 29, 8, 2],
    protons: 99,
    neutrons: 153,
    grupo: 13,
    periodo: 7,
    bloco: 'f'
  },
  {
    elemento: 'Férmio',
    simbolo: 'Fm',
    descricao: 'Um metal prateado brilhante. É altamente radioativo e é usado em pesquisas científicas.',
    massa: 257,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 30, 8, 2],
    protons: 100,
    neutrons: 157,
    grupo: 14,
    periodo: 7,
    bloco: 'f'
  },
  {
    elemento: 'Mendelévio',
    simbolo: 'Md',
    descricao: 'Um metal prateado brilhante. É altamente radioativo e é usado em pesquisas científicas.',
    massa: 258,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 31, 8, 2],
    protons: 101,
    neutrons: 157,
    grupo: 15,
    periodo: 7,
    bloco: 'f'
  },
  {
    elemento: 'Nobélio',
    simbolo: 'No',
    descricao: 'Um metal prateado brilhante. É altamente radioativo e é usado em pesquisas científicas.',
    massa: 259,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 32, 8, 2],
    protons: 102,
    neutrons: 157,
    grupo: 16,
    periodo: 7,
    bloco: 'f'
  },
  {
    elemento: 'Laurêncio',
    simbolo: 'Lr',
    descricao: 'Um metal prateado brilhante. É altamente radioativo e é usado em pesquisas científicas.',
    massa: 262,
    estado: 'Sólido',
    eletrons: [2, 8, 18, 32, 32, 8, 3],
    protons: 103,
    neutrons: 159,
    grupo: 17,
    periodo: 7,
    bloco: 'f'
  },
  {
    elemento: 'Rutherfórdio',
    simbolo: 'Rf',
    descricao: 'Um elemento artificial altamente radioativo. É produzido em laboratórios e é usado em pesquisas científicas.',
    massa: 267,
    estado: 'Desconhecido',
    eletrons: [2, 8, 18, 32, 32, 10, 2],
    protons: 104,
    neutrons: 163,
    grupo: 4,
    periodo: 7,
    bloco: 'd'
  },
  {
    elemento: 'Dúbnio',
    simbolo: 'Db',
    descricao: 'Um elemento artificial altamente radioativo. É produzido em laboratórios e é usado em pesquisas científicas.',
    massa: 270,
    estado: 'Desconhecido',
    eletrons: [2, 8, 18, 32, 32, 11, 2],
    protons: 105,
    neutrons: 165,
    grupo: 5,
    periodo: 7,
    bloco: 'd'
  },
  {
    elemento: 'Seabórgio',
    simbolo: 'Sg',
    descricao: 'Um elemento artificial altamente radioativo. É produzido em laboratórios e é usado em pesquisas científicas.',
    massa: 271,
    estado: 'Desconhecido',
    eletrons: [2, 8, 18, 32, 32, 12, 2],
    protons: 106,
    neutrons: 165,
    grupo: 6,
    periodo: 7,
    bloco: 'd'
  },
  {
    elemento: 'Bóhrio',
    simbolo: 'Bh',
    descricao: 'Um elemento artificial altamente radioativo. É produzido em laboratórios e é usado em pesquisas científicas.',
    massa: 270,
    estado: 'Desconhecido',
    eletrons: [2, 8, 18, 32, 32, 13, 2],
    protons: 107,
    neutrons: 163,
    grupo: 7,
    periodo: 7,
    bloco: 'd'
  },
  {
    elemento: 'Hássio',
    simbolo: 'Hs',
    descricao: 'Um elemento artificial altamente radioativo. É produzido em laboratórios e é usado em pesquisas científicas.',
    massa: 277,
    estado: 'Desconhecido',
    eletrons: [2, 8, 18, 32, 32, 14, 2],
    protons: 108,
    neutrons: 169,
    grupo: 8,
    periodo: 7,
    bloco: 'd'
  },
  {
    elemento: 'Meitnério',
    simbolo: 'Mt',
    descricao: 'Um elemento artificial altamente radioativo. É produzido em laboratórios e é usado em pesquisas científicas.',
    massa: 278,
    estado: 'Desconhecido',
    eletrons: [2, 8, 18, 32, 32, 15, 2],
    protons: 109,
    neutrons: 169,
    grupo: 9,
    periodo: 7,
    bloco: 'd'
  },
  {
    elemento: 'Darmstádio',
    simbolo: 'Ds',
    descricao: 'Um elemento artificial altamente radioativo. É produzido em laboratórios e é usado em pesquisas científicas.',
    massa: 281,
    estado: 'Desconhecido',
    eletrons: [2, 8, 18, 32, 32, 17, 2],
    protons: 110,
    neutrons: 171,
    grupo: 10,
    periodo: 7,
    bloco: 'd'
  },
  {
    elemento: 'Roentgênio',
    simbolo: 'Rg',
    descricao: 'Um elemento artificial altamente radioativo. É produzido em laboratórios e é usado em pesquisas científicas.',
    massa: 282,
    estado: 'Desconhecido',
    eletrons: [2, 8, 18, 32, 32, 18, 2],
    protons: 111,
    neutrons: 171,
    grupo: 11,
    periodo: 7,
    bloco: 'd'
  },
  {
    elemento: 'Copernício',
    simbolo: 'Cn',
    descricao: 'Um elemento artificial altamente radioativo. É produzido em laboratórios e é usado em pesquisas científicas.',
    massa: 285,
    estado: 'Desconhecido',
    eletrons: [2, 8, 18, 32, 32, 18, 3],
    protons: 112,
    neutrons: 173,
    grupo: 12,
    periodo: 7,
    bloco: 'd'
  },
  {
    elemento: 'Nihônio',
    simbolo: 'Nh',
    descricao: 'Um elemento artificial altamente radioativo. É produzido em laboratórios e é usado em pesquisas científicas.',
    massa: 286,
    estado: 'Desconhecido',
    eletrons: [2, 8, 18, 32, 32, 20, 2],
    protons: 113,
    neutrons: 173,
    grupo: 13,
    periodo: 7,
    bloco: 'p'
  },
  {
    elemento: 'Fleróvio',
    simbolo: 'Fl',
    descricao: 'Um elemento artificial altamente radioativo. É produzido em laboratórios e é usado em pesquisas científicas.',
    massa: 289,
    estado: 'Desconhecido',
    eletrons: [2, 8, 18, 32, 32, 21, 2],
    protons: 114,
    neutrons: 175,
    grupo: 14,
    periodo: 7,
    bloco: 'p'
  },
  {
    elemento: 'Moscóvio',
    simbolo: 'Mc',
    descricao: 'Um elemento artificial altamente radioativo. É produzido em laboratórios e é usado em pesquisas científicas.',
    massa: 289,
    estado: 'Desconhecido',
    eletrons: [2, 8, 18, 32, 32, 22, 2],
    protons: 115,
    neutrons: 174,
    grupo: 15,
    periodo: 7,
    bloco: 'p'
  },
  {
    elemento: 'Livermório',
    simbolo: 'Lv',
    descricao: 'Um elemento artificial altamente radioativo. É produzido em laboratórios e é usado em pesquisas científicas.',
    massa: 293,
    estado: 'Desconhecido',
    eletrons: [2, 8, 18, 32, 32, 23, 2],
    protons: 116,
    neutrons: 177,
    grupo: 16,
    periodo: 7,
    bloco: 'p'
  },
  {
    elemento: 'Tenessino',
    simbolo: 'Ts',
    descricao: 'Um elemento artificial altamente radioativo. É produzido em laboratórios e é usado em pesquisas científicas.',
    massa: 294,
    estado: 'Desconhecido',
    eletrons: [2, 8, 18, 32, 32, 24, 2],
    protons: 117,
    neutrons: 177,
    grupo: 17,
    periodo: 7,
    bloco: 'p'
  },
  {
    elemento: 'Oganessônio',
    simbolo: 'Og',
    descricao: 'Um elemento artificial altamente radioativo. É produzido em laboratórios e é usado em pesquisas científicas.',
    massa: 294,
    estado: 'Desconhecido',
    eletrons: [2, 8, 18, 32, 32, 25, 2],
    protons: 118,
    neutrons: 176,
    grupo: 18,
    periodo: 7,
    bloco: 'p'
  }
];
